### ISSUE TITLE
Add to Homebrew Core?

### ISSUE THREAD

**Issue by SeekingMeaning** [pemistahl/grex#18]
Now that grex is stable, perhaps it can be added to Homebrew/homebrew-core?

**Comment by SeekingMeaning** [comment]
Ah, it already has!

**Comment by waldyrious** [comment]
It's not in Homebrew core, though -- it's in a [separate tap](https://github.com/pemistahl/homebrew-formulas/blob/master/Formula/grex.rb). I agree it would make sense to add this to Homebrew proper, so we could install it with

    brew install grex

instead of

    brew install pemistahl/formulas/grex

**Comment by pemistahl** [comment]
@waldyrious It has already been added to homebrew-core, look [here](https://github.com/Homebrew/homebrew-core/pull/49714). I have left the separate tap until now because it is not possible to edit the docs on crates.io subsequently and I wanted to avoid different installation steps in the docs on GitHub and on crates.io.

Upon releasing grex 1.1.0, I will edit the docs to use homebrew-core and remove my own tap eventually.

**Comment by waldyrious** [comment]
> `@waldyrious` It has already been added to homebrew-core, look [here](https://github.com/Homebrew/homebrew-core/pull/49714). 

Ha 😄 I missed that indeed. Your reasoning for the current state of things makes perfect sense. Thanks for the explanation and looking forward to the upcoming release!
