### ISSUE TITLE
Much slower than Regexp::Assemble

### ISSUE THREAD

**Issue by twirrim** [pemistahl/grex#32]
Thanks for grex!  I love to see tools in this space.

Historically, I've used Regexp::Assemble for this kind of work, either via the full perl script, regexp-assemble, or via my own custom perl code that leveraged it.

The regexp-assemble script / module is available via CPAN, https://metacpan.org/pod/Regexp::Assemble, or via the package libregexp-assemble-perl on Ubuntu (not sure about other distributions).

I found it fairly straightforward to make a somewhat pathological case.  I used pwgen to make 100 random strings, 80 characters long, and spat them out to a file `pwgen 80 100 > testcase`, then ran it through multitime with it doing 5 attempts and reporting back.

This represents a similar-ish way I've used regexp-assemble in the past, feeding in a stream of unique request IDs to produce a combined regex to then use searching large log files, though I've not needed to do that for a while.

Feel free to disregard this issue if this doesn't meet your goals for grex.

regexp-assemble:
```
            Mean        Std.Dev.    Min         Median      Max
real        0.072       0.014       0.051       0.070       0.096       
user        0.058       0.011       0.046       0.062       0.075       
sys         0.015       0.010       0.005       0.008       0.030       
```
grex:
```
            Mean        Std.Dev.    Min         Median      Max
real        16.872      0.171       16.699      16.853      17.190      
user        14.745      0.178       14.541      14.745      15.062      
sys         2.125       0.019       2.104       2.126       2.157       
```

Performance of the actual regexes spat out the other side are variable.  Some of the test cases I made from real world data, regexp-assemble produced faster regexes, for others grex did.

Not sure if regexp-assemble might give you some interesting prior art to dig in to from a performance perspective.

**Comment by twirrim** [comment]
Another pretty pathological case, performance wise, is to point grex at a file containing these lines, which are just some sample lines of Unicode characters:
```
! " # $ % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? @ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z [ \ ] ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z { | } ~
¡ ¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ­ ® ¯ ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ÷ ø ù ú û ü ý þ ÿ
Ā ā Ă ă Ą ą Ć ć Ĉ ĉ Ċ ċ Č č Ď ď Đ đ Ē ē Ĕ ĕ Ė ė Ę ę Ě ě Ĝ ĝ Ğ ğ Ġ ġ Ģ ģ Ĥ ĥ Ħ ħ Ĩ ĩ Ī ī Ĭ ĭ Į į İ ı Ĳ ĳ Ĵ ĵ Ķ ķ ĸ Ĺ ĺ Ļ ļ Ľ ľ Ŀ ŀ Ł ł Ń ń Ņ ņ Ň ň ŉ Ŋ ŋ Ō ō Ŏ ŏ Ő ő Œ œ Ŕ ŕ Ŗ ŗ Ř ř Ś ś Ŝ ŝ Ş ş Š š Ţ ţ Ť ť Ŧ ŧ Ũ ũ Ū ū Ŭ ŭ Ů ů Ű ű Ų ų Ŵ ŵ Ŷ ŷ Ÿ Ź ź Ż ż Ž ž ſ
ƀ Ɓ Ƃ ƃ Ƅ ƅ Ɔ Ƈ ƈ Ɖ Ɗ Ƌ ƌ ƍ Ǝ Ə Ɛ Ƒ ƒ Ɠ Ɣ ƕ Ɩ Ɨ Ƙ ƙ ƚ ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ ƣ Ƥ ƥ Ʀ Ƨ ƨ Ʃ ƪ ƫ Ƭ ƭ Ʈ Ư ư Ʊ Ʋ Ƴ ƴ Ƶ ƶ Ʒ Ƹ ƹ ƺ ƻ Ƽ ƽ ƾ ƿ ǀ ǁ ǂ ǃ Ǆ ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ Ǎ ǎ Ǐ ǐ Ǒ ǒ Ǔ ǔ Ǖ ǖ Ǘ ǘ Ǚ ǚ Ǜ ǜ ǝ Ǟ ǟ Ǡ ǡ Ǣ ǣ Ǥ ǥ Ǧ ǧ Ǩ ǩ Ǫ ǫ Ǭ ǭ Ǯ ǯ ǰ Ǳ ǲ ǳ Ǵ ǵ Ƕ Ƿ Ǹ ǹ Ǻ ǻ Ǽ ǽ Ǿ ǿ ...
ɐ ɑ ɒ ɓ ɔ ɕ ɖ ɗ ɘ ə ɚ ɛ ɜ ɝ ɞ ɟ ɠ ɡ ɢ ɣ ɤ ɥ ɦ ɧ ɨ ɩ ɪ ɫ ɬ ɭ ɮ ɯ ɰ ɱ ɲ ɳ ɴ ɵ ɶ ɷ ɸ ɹ ɺ ɻ ɼ ɽ ɾ ɿ ʀ ʁ ʂ ʃ ʄ ʅ ʆ ʇ ʈ ʉ ʊ ʋ ʌ ʍ ʎ ʏ ʐ ʑ ʒ ʓ ʔ ʕ ʖ ʗ ʘ ʙ ʚ ʛ ʜ ʝ ʞ ʟ ʠ ʡ ʢ ʣ ʤ ʥ ʦ ʧ ʨ ʩ ʪ ʫ ʬ ʭ
ʰ ʱ ʲ ʳ ʴ ʵ ʶ ʷ ʸ ʹ ʺ ʻ ʼ ʽ ʾ ʿ ˀ ˁ ˂ ˃ ˄ ˅ ˆ ˇ ˈ ˉ ˊ ˋ ˌ ˍ ˎ ˏ ː ˑ ˒ ˓ ˔ ˕ ˖ ˗ ˘ ˙ ˚ ˛ ˜ ˝ ˞ ˟ ˠ ˡ ˢ ˣ ˤ ˥ ˦ ˧ ˨ ˩ ˪ ˫ ˬ ˭ ˮ
ʹ ͵ ͺ ; ΄ ΅ Ά · Έ Ή Ί Ό Ύ Ώ ΐ Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω Ϊ Ϋ ά έ ή ί ΰ α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω ϊ ϋ ό ύ ώ ϐ ϑ ϒ ϓ ϔ ϕ ϖ ϗ Ϙ ϙ Ϛ ϛ Ϝ ϝ Ϟ ϟ Ϡ ϡ Ϣ ϣ Ϥ ϥ Ϧ ϧ Ϩ ϩ Ϫ ϫ Ϭ ϭ Ϯ ϯ ϰ ϱ ϲ ϳ ϴ ϵ ϶
```

grex sits at 100% cpu usage for a fair while with that.

**Comment by pemistahl** [comment]
Hi @twirrim, thank you for this evaluation. I appreciate that.

I've already stated my opinion on this matter in [another issue](https://github.com/pemistahl/grex/issues/25). For a tool like *grex*, performance in terms of raw speed of execution is not essential imho. Nobody will ever use this tool to generate a regex from 100 strings, each 80 characters long. At least not without manual inspection of the result. Execution speed does not matter in this case.

Your comparison with the Perl tool is difficult imho, because it combines multiple regexes into a single one. *grex*, however, assembles a regex from test cases that it matches. So the algorithms for both tools are different which does not make a performance comparison well-founded.

In future releases, I will surely optimize performance where it is feasible. Much more important is the correctness of the results imho. I'm closing this issue now but will gladly refer back to it if I work on performance aspects. So thanks again.
